import Images from "../../common/image";
const restaurantList = [
  {
    id: "01",
    image: Images.noodles,
    item_startp_price: "Items at 99",
    restaurant_name: "Apni Rasoi Family Dhaba",
    restaurant_rating: "4.0 (1.2K+ ratings)",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    restaurant_food_colture: "North Indian, Indian",
    item_status: "available",
    fast_dilever: "yes",
    item_price_quantity: "₹250 for two",
  },
  {
    id: "02",
    image: Images.bakery,
    item_startp_price: "10% off above Rs 1099",
    restaurant_name: "Bakery Word",
    restaurant_rating: "4.3",
    deliver_timing: "45-45 mins",
    restaurant_item_name: "Bakery, Ice Cream, Snacks, Cold drinks, Bread",
    restaurant_location: "Indirapuram",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "03",
    image: Images.biryani,
    item_startp_price: "Start Rs 30",
    restaurant_name: "biryani",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "04",
    image: Images.pizza,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "05",
    image: Images.rolls,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },

  {
    id: "06",
    image: Images.parantha,
    item_startp_price: "Items at 199",
    restaurant_name: "pizza hutdsfdsaf",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    category_veg: "yes",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "07",
    image: Images.pureveg,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "08",
    image: Images.tea,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "09",
    image: Images.gulabjamun,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: ". 25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    category_veg: "yes",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "10",
    image: Images.coffee,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: ". 25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "11",
    image: Images.noodles,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "12",
    image: Images.bakery,
    item_startp_price: "10% off above Rs 1099",
    restaurant_name: "Bakery Word",
    restaurant_rating: "4.3",
    deliver_timing: "45-45 mins",
    restaurant_item_name: "Bakery, Ice Cream, Snacks, Cold drinks, Bread",
    restaurant_location: "Indirapuram",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "13",
    image: Images.biryani,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "not available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "14",
    image: Images.pizza,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "15",
    image: Images.rolls,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },

  {
    id: "16",
    image: Images.parantha,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "17",
    image: Images.pureveg,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "18",
    image: Images.tea,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "19",
    image: Images.gulabjamun,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: ". 25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "20",
    image: Images.coffee,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: ". 25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    restaurant_food_colture: "North Indian, Indian",
  },
  {
    id: "21",
    image: Images.noodles,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Pizza",
    restaurant_location: "Noida",
    item_status: "available",
    fast_dilever: "yes",
    restaurant_food_colture: "North Indian, Indian",
  },
];

export default restaurantList;
