import Images from "../../common/image";
const resData = [
  {
    id: "01",
    image: Images.paneerTikka,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    rating_comment: "18",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Paneer Tikka",
    restaurant_location: "Noida",
    item_status: "available",
    fast_dilever: "yes",
    veg: "yes",
    price: "Rs 270",
    item_description:
      "Grilled and marinated cubes of tender Indian cheese, bursting with flavors, to tantalize your taste buds.",
  },
  {
    id: "02",
    image: Images.vegManchurian,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "2.0",
    rating_comment: "24",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Veg Manchurian",
    restaurant_location: "Noida",
    item_status: "available",
    fast_dilever: "yes",
    veg: "yes",
    price: "Rs 220",
    item_description:
      "A delectable vegetarian delight, bursting with flavor and perfect for a hearty starter.",
  },
  {
    id: "03",
    image: Images.vegLollipop,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "5.0",
    rating_comment: "7",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Veg Lollipop",
    restaurant_location: "Noida",
    item_status: "available",
    fast_dilever: "yes",
    veg: "yes",
    price: "Rs 260",
    item_description:
      "Mouthwatering vegetarian delight perfect for your starters!",
  },
  {
    id: "04",
    image: Images.bhindiMasala,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "3.0",
    rating_comment: "12",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Bhindi Masala",
    restaurant_location: "Noida",
    item_status: "available",
    fast_dilever: "yes",
    veg: "yes",
    price: "Rs 220",
    item_description:
      "A flavorful and aromatic vegetarian main course that will tantalize your taste buds with its rich blend of flavors.",
  },
  {
    id: "05",
    image: Images.chanaMasala,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "5.0",
    rating_comment: "7",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Chana Masala",
    restaurant_location: "Noida",
    item_status: "available",
    fast_dilever: "yes",
    veg: "yes",
    price: "Rs 230",
    item_description:
      "A flavorful and aromatic Indian curry dish packed with rich flavors and textures.",
  },

  {
    id: "06",
    image: Images.sevTamatar,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.5",
    rating_comment: "14",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Sev Tamatar",
    restaurant_location: "Noida",
    item_status: "available",
    fast_dilever: "yes",
    veg: "yes",
    price: "Rs 220",
    item_description:
      "A delectable vegetarian main course featuring a delightful combination of flavors that will leave your taste buds wanting more.",
  },
  {
    id: "07",
    image: Images.mushroomMasala,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.9",
    rating_comment: "25",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Mushroom Masala",
    restaurant_location: "Noida",
    item_status: "available",
    fast_dilever: "yes",
    veg: "yes",
    price: "Rs 260",
    item_description:
      "A delectable and flavorful vegetarian main course featuring succulent mushrooms cooked to perfection in a rich, aromatic sauce.",
  },
  {
    id: "08",
    image: Images.sahipaneer,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "4.2",
    rating_comment: "104",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Shahi Paneer",
    restaurant_location: "Noida",
    item_status: "available",
    fast_dilever: "yes",
    veg: "yes",
    price: "Rs 150",
    item_description:
      "A creamy and aromatic Indian delight of succulent cottage cheese cooked in a luscious, flavorful sauce.",
  },
  {
    id: "09",
    image: Images.biryani,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "3.7",
    rating_comment: "18",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Chicken Biryani",
    restaurant_location: "Noida",
    item_status: "available",
    fast_dilever: "yes",
    veg: "no",
    price: "Rs 430",
    item_description:
      "A luscious and creamy vegetarian delight featuring a perfect blend of spinach and soft pieces of homemade cheese.",
  },
  {
    id: "10",
    image: Images.cholePaneer,
    item_startp_price: "Items at 99",
    restaurant_name: "pizza hut",
    restaurant_rating: "2.5",
    rating_comment: "7",
    deliver_timing: "25-30 mins",
    restaurant_item_name: "Chole Paneer",
    restaurant_location: "Noida",
    item_status: "available",
    fast_dilever: "yes",
    veg: "yes",
    price: "Rs 260",
    item_description:
      "A flavorful and hearty combination of tender paneer and protein-packed chickpeas in a delectable gravy.",
  },
];

export default resData;
